# Generated by Django 5.1.6 on 2025-02-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_appointment_service_alter_appointment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ManyToManyField(to='app.service'),
        ),
    ]
