# Generated by Django 5.1.6 on 2025-02-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_menusection_delete_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuSection',
            new_name='MenuSelection',
        ),
    ]
