# Generated by Django 5.1.6 on 2025-02-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_booking_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='total_cost',
        ),
    ]
