# Generated by Django 5.1.6 on 2025-02-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_price_service_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='total_cost',
            new_name='price',
        ),
    ]
