# Generated by Django 5.1.6 on 2025-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_total_cost_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bi_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(),
        ),
    ]
